### ISSUE TITLE
update static graphics for final creek categories

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tidalcreek-dash#3]
ed2f4278b1ca1de41ddbb17f778fb75ecc9da979

**Comment by fawda123** [comment]
@mikewessel can you please send me an updated version of this graphic with the categories from the manuscript? 
https://github.com/tbep-tech/tidalcreek-dash/blob/master/www/tidalcreekreport.PNG

**Comment by mikewessel** [comment]
![Slide2](https://user-images.githubusercontent.com/15806688/88107206-b44fe080-cb74-11ea-8613-e68ae6d25148.JPG)
![Slide1](https://user-images.githubusercontent.com/15806688/88107207-b4e87700-cb74-11ea-929f-8d2263e966c1.JPG)

**Comment by mikewessel** [comment]
The vertical lines line up better in this version. 
![Slide1](https://user-images.githubusercontent.com/15806688/88107466-1dcfef00-cb75-11ea-9d4b-fc416a191b17.JPG)
![Slide2](https://user-images.githubusercontent.com/15806688/88107467-1e688580-cb75-11ea-99fc-d200ec8610ab.JPG)
