### ISSUE TITLE
Creek_selectR

### ISSUE THREAD

**Issue by mikewessel** [tbep-tech/tidalcreek-dash#4]
@fawda123 Check out interactive map on creekstats page https://tbep-tech.github.io/tidalcreek-stats/
I think this will be a handy tool but it also highlighted a couple issues with line file that could be improved. We can improve the line file in GIS but I think it may be better to wait to update the dashboard once the creek_selectR program is up and running. No rush, just adding as a reminder to incorporate updated line file once we get creek_selectR working

**Comment by fawda123** [comment]
Hell yea, that's awesome. I think this is what I need to wrap my head around the creek assignments.  And yes, `creek_selectR` is still in the queue, but this map will go a long way to help that process.

**Comment by mikewessel** [comment]
Great- I talked to Steve who suggested using a flat buffer. We are going to go ahead and do that which should solve a lot of little bugs with selection. Don’t get to far into the creek selectR.end until we talk or I get one more chance to organize it. It may still be overly confusing.
